### ISSUE TITLE
Module build failed

### ISSUE THREAD

**Issue by StrangeTcy** [opencog/external-tools#120]
On Ubuntu 16.04 `npm install` works fine, but trying `npm start -- --port 3030` leads to the following error:
```
ERROR in ./node_modules/css-loader?{"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader?{"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":false,"precision":8,"includePaths":[]}!./src/theme.scss
Module build failed: Error: ENOENT: no such file or directory, scandir '~/opencog/external-tools/AtomSpaceExplorer/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.getInstalledBinaries (~/opencog/external-tools/AtomSpaceExplorer/node_modules/node-sass/lib/extensions.js:128:13)
    at foundBinariesList (~/opencog/external-tools/AtomSpaceExplorer/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (~/opencog/external-tools/AtomSpaceExplorer/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (~/opencog/external-tools/AtomSpaceExplorer/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (~/opencog/external-tools/AtomSpaceExplorer/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (~/opencog/external-tools/AtomSpaceExplorer/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (~/opencog/external-tools/AtomSpaceExplorer/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (module.js:643:30)
 @ ./src/theme.scss 4:14-186
 @ multi ./src/styles.css ./src/theme.scss

webpack: Failed to compile.

```

`node -v` is v8.9.4, and `npm -v` is 5.6.0

**Comment by StrangeTcy** [comment]
Manually installing node-sass and then running `sudo npm install --unsafe-perm=true --allow-root` somehow fixed this issue
