### ISSUE TITLE
"npm start" crashes after successful "npm install"

### ISSUE THREAD

**Issue by mjsduncan** [opencog/external-tools#95]
don't know what other info is helpful (list of package versions is insanely long).  here is log file:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@5.4.2
3 info using node@v8.4.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle front-end@0.0.0~prestart: front-end@0.0.0
6 info lifecycle front-end@0.0.0~start: front-end@0.0.0
7 verbose lifecycle front-end@0.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle front-end@0.0.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/mjsd/oc/external-tools/AtomSpaceExplorer/node_modules/.bin:/usr/local/cuda-9.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle front-end@0.0.0~start: CWD: /home/mjsd/oc/external-tools/AtomSpaceExplorer
10 silly lifecycle front-end@0.0.0~start: Args: [ '-c', 'ng serve' ]
11 silly lifecycle front-end@0.0.0~start: Returned: code: 1  signal: null
12 info lifecycle front-end@0.0.0~start: Failed to exec start script
13 verbose stack Error: front-end@0.0.0 start: `ng serve`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid front-end@0.0.0
15 verbose cwd /home/mjsd/oc/external-tools/AtomSpaceExplorer
16 verbose Linux 4.4.0-97-generic
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v8.4.0
19 verbose npm  v5.4.2
20 error code ELIFECYCLE
21 error errno 1
22 error front-end@0.0.0 start: `ng serve`
22 error Exit status 1
23 error Failed at the front-end@0.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by TScottJ** [comment]
Hey @mjsduncan , just want to confirm if you were using the older glimpse visualizer or the new AtomSpaceExplorer that we added a couple of days ago? If you're still using the old one (which we've moved to an 'Obsolete' sub-folder), would you be able to try using the new one, and let us know if still any issues? Cheers!

**Comment by mjsduncan** [comment]
this is AtomSpaceExplorer from a fresh clone of external-tools.  i forgot to mention this is on ubuntu 16.04 with
```
$ npm -v
5.4.2
$ node -v
v8.4.0
```

**Comment by TScottJ** [comment]
Roger that, will get our dev (Stephen) to take a look. I know he's been using the Vagrant method (http://wiki.opencog.org/w/Building_OpenCog#Run_Vagrant), rather than a native Ubuntu box, if that makes any difference.

**Comment by mjsduncan** [comment]
after latest update i'm getting the same error.  i've included the shell output this time as it includes
info starting with `at TypeError: ts.createModuleResolutionCache is not a function` that isn't in the log file.
```
$ npm start

> front-end@0.0.0 start /home/mjsd/oc/external-tools/AtomSpaceExplorer
> ng serve

ts.createModuleResolutionCache is not a function
TypeError: ts.createModuleResolutionCache is not a function
    at AotPlugin._setupOptions (/home/mjsd/oc/external-tools/AtomSpaceExplorer/node_modules/@ngtools/webpack/src/plugin.js:146:42)
    at new AotPlugin (/home/mjsd/oc/external-tools/AtomSpaceExplorer/node_modules/@ngtools/webpack/src/plugin.js:30:14)
    at _createAotPlugin (/home/mjsd/oc/external-tools/AtomSpaceExplorer/node_modules/@angular/cli/models/webpack-configs/typescript.js:55:12)
    at Object.getNonAotConfig (/home/mjsd/oc/external-tools/AtomSpaceExplorer/node_modules/@angular/cli/models/webpack-configs/typescript.js:72:19)
    at NgCliWebpackConfig.buildConfig (/home/mjsd/oc/external-tools/AtomSpaceExplorer/node_modules/@angular/cli/models/webpack-config.js:29:37)
    at Class.run (/home/mjsd/oc/external-tools/AtomSpaceExplorer/node_modules/@angular/cli/tasks/serve.js:71:98)
    at check_port_1.checkPort.then.port (/home/mjsd/oc/external-tools/AtomSpaceExplorer/node_modules/@angular/cli/commands/serve.js:121:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! front-end@0.0.0 start: `ng serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the front-end@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mjsd/.npm/_logs/2017-10-16T06_13_51_346Z-debug.log

$ cat /home/mjsd/.npm/_logs/2017-10-16T06_13_51_346Z-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@5.5.1
3 info using node@v8.4.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle front-end@0.0.0~prestart: front-end@0.0.0
6 info lifecycle front-end@0.0.0~start: front-end@0.0.0
7 verbose lifecycle front-end@0.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle front-end@0.0.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/mjsd/oc/external-tools/AtomSpaceExplorer/node_modules/.bin:/usr/local/cuda-9.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle front-end@0.0.0~start: CWD: /home/mjsd/oc/external-tools/AtomSpaceExplorer
10 silly lifecycle front-end@0.0.0~start: Args: [ '-c', 'ng serve' ]
11 silly lifecycle front-end@0.0.0~start: Returned: code: 1  signal: null
12 info lifecycle front-end@0.0.0~start: Failed to exec start script
13 verbose stack Error: front-end@0.0.0 start: `ng serve`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid front-end@0.0.0
15 verbose cwd /home/mjsd/oc/external-tools/AtomSpaceExplorer
16 verbose Linux 4.4.0-97-generic
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v8.4.0
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error front-end@0.0.0 start: `ng serve`
22 error Exit status 1
23 error Failed at the front-end@0.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by mjsduncan** [comment]
after doing a fresh clone this works for me.  after the initial fail but before applying the last commit i tried updating packages according the many warnings suggesting/insisting i do so.  undoing these upgrades with the fresh clone did the trick.  will reliance on outdated packages be an issue going forward?

**Comment by TScottJ** [comment]
Good question about outdated packages...have assigned to @sshermz , he can look into that, though we'll leave this issue closed (can open another if need be).

**Comment by sshermz** [comment]
@mjsduncan , glad you got past this. I've been working on urgent features, so haven't had a chance to update the packages, which are mostly as-is from the originating source code. But I have this on my TODO list now. Feel free to open a new issue to track this as @TScottJ mentioned.
